In [1]:
import warnings

warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from gensim import downloader

In [14]:
%load_ext nb_black

<IPython.core.display.Javascript object>

In [31]:
def vectorize(description, vectorizer):
    arr = description.split(" ")
    r = None
    for a in arr:
        try:
            if r is None:
                r = np.array([vectorizer[a]])
            else:
                r = np.vstack([r, vectorizer[a]])
        except KeyError:
            pass
    if r is None:
        return np.array([])
    return r


def padArr(arr, arr_size, tot_size):
    if len(arr) == 0:
        return np.zeros((tot_size, arr_size))
    for i in range(len(arr), tot_size):
        arr = np.vstack([arr, np.zeros(arr_size)])
    return arr


def padSer(ser, arr_size):
    tot_size = ser.apply(len).max()
    return ser.apply(lambda arr: padArr(arr, arr_size, tot_size))

<IPython.core.display.Javascript object>

In [3]:
word_2_vec = downloader.load('word2vec-google-news-300')

In [29]:
w2v_len = word_2_vec["hola"].shape[0]

<IPython.core.display.Javascript object>

In [5]:
train = catalog.load("train_contract_value_rnn")

[08/13/22 19:21:53] INFO     Loading data from 'train_contract_value_rnn' (ParquetDataSet)...   ]8;id=846775;file:///opt/homebrew/Caskroom/miniforge/base/envs/dm_project/lib/python3.10/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=974535;file:///opt/homebrew/Caskroom/miniforge/base/envs/dm_project/lib/python3.10/site-packages/kedro/io/data_catalog.py#343\343]8;;\

In [8]:
i = 0

In [9]:
batch_size=500

In [10]:
num_batches = np.ceil(len(train)/batch_size)

In [16]:
train_other = (
    train.drop(["index", "full_contract_description", "log_valor_del_contrato"], axis=1)
    .iloc[i * batch_size : (i + 1) * batch_size]
    .values
)

<IPython.core.display.Javascript object>

In [20]:
train_text = (
    train["full_contract_description"]
    .iloc[i * batch_size : (i + 1) * batch_size]
    .apply(lambda x: vectorize(x, word_2_vec))
)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [32]:
train_text = padSer(train_text, w2v_len).values

<IPython.core.display.Javascript object>

In [ ]:
train_tex.shapet

array([array([[-0.03833008, -0.18457031, -0.00595093, ..., -0.16503906,
                0.15722656,  0.14257812],
              [ 0.1875    ,  0.01574707, -0.05859375, ..., -0.08154297,
               -0.17089844, -0.15429688],
              [ 0.02258301, -0.03417969,  0.0703125 , ..., -0.06835938,
                0.04052734,  0.09521484],
              ...,
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ],
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ],
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ]])                             ,
       array([[-0.03833008, -0.18457031, -0.00595093, ..., -0.16503906,
                0.15722656,  0.14257812],
              [-0.01031494, -0.08056641,  0.05175781, ..., -0.08447266,
                0.03930664,  0.27148438],
              [-0.09667969,  0.00231934,  0.11425781, ..., -0.0111084 ,
                0.07666016,  0.13476562],
              ...,
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ],
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ],
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ]])                             ,
       array([[-0.03833008, -0.18457031, -0.00595093, ..., -0.16503906,
                0.15722656,  0.14257812],
              [-0.25390625, -0.08789062,  0.15527344, ..., -0.05029297,
               -0.29101562,  0.07177734],
              [-0.04125977,  0.11914062,  0.11181641, ..., -0.15429688,
                0.05712891,  0.18066406],
              ...,
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ],
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ],
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ]])                             ,
       array([[-0.03833008, -0.18457031, -0.00595093, ..., -0.16503906,
                0.15722656,  0.14257812],
              [-0.01031494, -0.08056641,  0.05175781, ..., -0.08447266,
                0.03930664,  0.27148438],
              [ 0.00665283, -0.03930664,  0.06298828, ..., -0.07080078,
                0.01031494,  0.04931641],
              ...,
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ],
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ],
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ]])                             ,
       array([[-0.04125977,  0.00543213,  0.09033203, ..., -0.16992188,
                0.03222656,  0.11669922],
              [-0.0100708 , -0.06738281,  0.08496094, ..., -0.12890625,
               -0.01513672,  0.07763672],
              [ 0.00759888, -0.10351562,  0.05737305, ..., -0.14550781,
                0.12451172,  0.16503906],
              ...,
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ],
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ],
              [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                0.        ,  0.        ]])                             ,
       array([[-0.06494141, -0.0279541 ,  0.00294495, ..., -0.03808594,
                0.09082031,  0.11962891],
              [-0.04736328,  0.00564575,  0.04443359, ...,  0.04980469,
               -0.09277344,  0.06347656],
              [ 0.01092529,  0.0177002 ,  0.08251953, ..., -0.06884766,
                0.02990723,  0

In [25]:
train_text.iloc[190].shape

(8, 300)

<IPython.core.display.Javascript object>

In [7]:
train.columns

Index(['index', 'full_contract_description', 'duration_days', 'Agricultura',
       'Hidrocarburos', 'Manufactura', 'ServiciosPublicos', 'Construccion',
       'Comercio', 'Comunicaciones', 'Financiero', 'Inmobiliaria',
       'Profesionales', 'AdministracionPublica', 'Artisticas', 'ValorAgregado',
       'Impuestos', 'PIB', 'Poblacion', 'log_valor_del_contrato',
       'dias_adicionados', 'days_ref', 'orden_nacional', 'orden_territorial',
       'modalidad_de_contratacion_contratacion directa',
       'modalidad_de_contratacion_licitacion publica',
       'modalidad_de_contratacion_menor cuantia',
       'modalidad_de_contratacion_otro',
       'modalidad_de_contratacion_regimen especial',
       'modalidad_de_contratacion_subasta'],
      dtype='object')

In [ ]:
class ContractDataset:
    def __init__(
        self, 
        df,
        vectorizer,
        batch_size=500,
    ):
        self.df = df
        self.batch_size = batch_size
        self.num_batches = np.ceil(len(df)/batch_size)
        self.vectorizer = vectorizer
    def __len__(self):
        return self.size

    def __getitem__(self,idx):
        same = None
        sample_inds=None
        if np.random.rand() < self.prop_same:
            # Generation of pictures from same person
            person_to_sample = self.val_counts_rep[
                self.val_counts_rep.cumsum() > np.random.randint((self.val_counts_rep).sum())
            ].index[0]
            sample_inds = np.random.choice(
                self.df[self.df["name"] == person_to_sample]["address"].values, 2,
            )
            same = 1
        else:
            # Generation of pictures from different people
            sample_inds = np.random.choice(self.df.index, 2)
            while self.df.loc[sample_inds[0], "name"] == self.df.loc[sample_inds[1], "name"]:
                sample_inds = np.random.choice(self.df.index, 2)
            sample_inds = tuple(self.df.loc[sample_inds,'address'])
            same = 0
        im_1 = self.randomflip(imread(CWD + FACES_DIR + "/" + sample_inds[0]) / 127.5 - 1)
        im_2 = self.randomflip(imread(CWD + FACES_DIR + "/" + sample_inds[1]) / 127.5 - 1)
        
        return(
            np.concatenate([im_1,im_2]),
            same,
        )
    
    def __call__(self):
        for i in range(self.__len__()):
            yield self.__getitem__(i)
            
    def randomflip(self, arr):
        if self.train and (np.random.rand() > 0.5):
            return arr[:, np.arange(arr.shape[1] - 1, -1, -1), :]
        return arr